do $$
declare
  demo_user_id uuid := '11111111-1111-4111-8111-111111111111';
  demo_email text := 'demo@lingualog.dev';
  demo_password text := 'DemoPass123!';
begin
  insert into auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    raw_app_meta_data,
    raw_user_meta_data,
    created_at,
    updated_at,
    confirmation_token,
    email_change,
    email_change_token_new,
    recovery_token
  )
  values (
    '00000000-0000-0000-0000-000000000000',
    demo_user_id,
    'authenticated',
    'authenticated',
    demo_email,
    crypt(demo_password, gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{"username":"Demo Learner","full_name":"Demo Learner"}'::jsonb,
    now() - interval '90 days',
    now(),
    '',
    '',
    '',
    ''
  )
  on conflict (id) do update
  set
    email = excluded.email,
    encrypted_password = excluded.encrypted_password,
    raw_user_meta_data = excluded.raw_user_meta_data,
    updated_at = now();

  insert into auth.identities (
    id,
    user_id,
    identity_data,
    provider,
    provider_id,
    created_at,
    updated_at,
    last_sign_in_at
  )
  values (
    gen_random_uuid(),
    demo_user_id,
    jsonb_build_object('sub', demo_user_id::text, 'email', demo_email),
    'email',
    demo_email,
    now() - interval '90 days',
    now(),
    now()
  )
  on conflict (provider, provider_id) do update
  set
    identity_data = excluded.identity_data,
    updated_at = now(),
    last_sign_in_at = now();

  insert into public.users (id, email, username)
  values (demo_user_id, demo_email, 'Demo Learner')
  on conflict (id) do update
  set
    email = excluded.email,
    username = excluded.username,
    updated_at = now();

  insert into public.user_settings (
    user_id,
    native_language,
    target_languages,
    email_notifications,
    push_notifications,
    daily_reminders,
    weekly_progress,
    reminder_time,
    theme,
    app_language,
    sound_effects,
    animations,
    difficulty_level,
    daily_goal,
    weekly_goal,
    auto_save,
    show_hints,
    public_profile,
    share_progress,
    analytics_opt_in,
    interface_lang,
    native_lang,
    default_target_lang,
    explanation_mode,
    immersion_level,
    strictness,
    formality
  )
  values (
    demo_user_id,
    'en',
    array['es', 'fr'],
    true,
    true,
    true,
    true,
    '08:30',
    'system',
    'en',
    true,
    true,
    'intermediate',
    120,
    800,
    true,
    true,
    false,
    false,
    true,
    'en',
    'en',
    'es',
    'bilingual',
    2,
    'medium',
    'neutral'
  )
  on conflict (user_id) do update
  set
    target_languages = excluded.target_languages,
    daily_goal = excluded.daily_goal,
    weekly_goal = excluded.weekly_goal,
    default_target_lang = excluded.default_target_lang,
    explanation_mode = excluded.explanation_mode,
    explanation_mode_explicit = false,
    immersion_level = excluded.immersion_level,
    strictness = excluded.strictness,
    formality = excluded.formality,
    updated_at = now();

  -- Spanish profile matches the seeded immersion (2 → B1 is the one-time map only).
  insert into public.user_language_profiles (user_id, l2, immersion_level, proficiency)
  values (demo_user_id, 'es', 2, 'B1'), (demo_user_id, 'fr', 2, 'A2')
  on conflict (user_id, l2) do update
  set
    immersion_level = excluded.immersion_level,
    proficiency = excluded.proficiency,
    active = true,
    updated_at = now();

  delete from public.word_ai_cache
  where word_vocabulary_id in (
    select id from public.user_vocabulary where user_id = demo_user_id
  );
  delete from public.user_vocabulary where user_id = demo_user_id;
  delete from public.journal_entries where user_id = demo_user_id;
end
$$;

insert into public.journal_entries (
  id,
  user_id,
  title,
  language,
  original_text,
  corrected,
  rewrite,
  score,
  tone,
  translation,
  explanation,
  rubric,
  grammar_suggestions,
  new_words,
  target_language,
  ui_language_snapshot,
  explanation_language_snapshot,
  translation_policy_snapshot,
  proficiency_estimate,
  analysis_status,
  analysis_model,
  created_at
)
values
  (
    '20000000-0000-4000-8000-000000000001',
    '11111111-1111-4111-8111-111111111111',
    'Cafe and Study Plan',
    'es',
    'Hoy fui al cafe para estudiar frances. Escribi mis metas en una libreta y me senti muy motivado.',
    'Hoy fui al cafe para estudiar frances. Escribi mis metas en una libreta y me senti muy motivado.',
    'Hoy fui al cafe para estudiar frances. Anote mis metas en una libreta y me senti muy motivado.',
    84,
    'Hopeful',
    'Today I went to the cafe to study French. I wrote my goals in a notebook and felt very motivated.',
    'Great clarity. Keep using time markers like "Hoy" and add accents when possible.',
    '{"grammar":82,"vocabulary":84,"complexity":78}'::jsonb,
    '[{"id":"gs1","original":"estudiar frances","corrected":"estudiar frances","note":"Remember accents when typing carefully: frances -> frances."}]'::jsonb,
    '[{"id":"nw1","term":"meta","pos":"noun","definition":"goal or objective","example":"Mi meta es practicar cada dia.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '11 days'
  ),
  (
    '20000000-0000-4000-8000-000000000002',
    '11111111-1111-4111-8111-111111111111',
    'After Work Reflection',
    'es',
    'Despues del trabajo cocine sopa de verduras y hable con mi hermana por telefono.',
    'Despues del trabajo, cocine sopa de verduras y hable con mi hermana por telefono.',
    'Despues del trabajo cocine una sopa de verduras y hable con mi hermana por telefono.',
    80,
    'Reflective',
    'After work, I cooked vegetable soup and talked with my sister on the phone.',
    'Solid sentence flow. Add commas to separate opening time phrases.',
    '{"grammar":79,"vocabulary":81,"complexity":74}'::jsonb,
    '[{"id":"gs2","original":"Despues del trabajo cocine","corrected":"Despues del trabajo, cocine","note":"Use a comma after introductory phrases."}]'::jsonb,
    '[{"id":"nw2","term":"verduras","pos":"noun","definition":"vegetables","example":"Compre verduras frescas en el mercado.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '10 days'
  ),
  (
    '20000000-0000-4000-8000-000000000003',
    '11111111-1111-4111-8111-111111111111',
    'Weekend with Friends',
    'es',
    'El sabado visite a mis amigos y jugamos juegos de mesa hasta medianoche.',
    'El sabado visite a mis amigos y jugamos juegos de mesa hasta medianoche.',
    'El sabado visite a mis amigos y estuvimos jugando juegos de mesa hasta medianoche.',
    86,
    'Excited',
    'On Saturday I visited my friends and we played board games until midnight.',
    'Nice use of past tense. Try varied connectors for longer paragraphs.',
    '{"grammar":85,"vocabulary":87,"complexity":80}'::jsonb,
    '[{"id":"gs3","original":"jugamos juegos","corrected":"estuvimos jugando juegos","note":"Progressive past adds natural rhythm in storytelling."}]'::jsonb,
    '[{"id":"nw3","term":"medianoche","pos":"noun","definition":"midnight","example":"Llegamos a casa despues de la medianoche.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '9 days'
  ),
  (
    '20000000-0000-4000-8000-000000000004',
    '11111111-1111-4111-8111-111111111111',
    'French Practice',
    'fr',
    'Ce matin jai lu un article en francais et jai appris trois nouvelles expressions.',
    'Ce matin, jai lu un article en francais et jai appris trois nouvelles expressions.',
    'Ce matin, jai lu un article en francais et jai retenu trois nouvelles expressions.',
    82,
    'Determined',
    'This morning I read an article in French and learned three new expressions.',
    'Good structure. In French, punctuation around opening time phrases improves readability.',
    '{"grammar":81,"vocabulary":83,"complexity":77}'::jsonb,
    '[{"id":"gs4","original":"Ce matin jai","corrected":"Ce matin, jai","note":"Add a comma after introductory expressions."}]'::jsonb,
    '[{"id":"nw4","term":"expression","pos":"noun","definition":"common phrase or expression","example":"Cette expression est tres utile.","proficiency":"intermediate"}]'::jsonb,
    'fr',
    'en',
    'en,fr',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '8 days'
  ),
  (
    '20000000-0000-4000-8000-000000000005',
    '11111111-1111-4111-8111-111111111111',
    'Rainy Day',
    'es',
    'Hoy llovia mucho entonces me quede en casa para estudiar vocabulario.',
    'Hoy llovia mucho, entonces me quede en casa para estudiar vocabulario.',
    'Como hoy llovia mucho, me quede en casa para repasar vocabulario.',
    83,
    'Neutral',
    'Today it rained a lot, so I stayed home to study vocabulary.',
    'Excellent causal connector. Try replacing repeated verbs with synonyms.',
    '{"grammar":84,"vocabulary":82,"complexity":79}'::jsonb,
    '[{"id":"gs5","original":"llovia mucho entonces","corrected":"llovia mucho, entonces","note":"Comma helps separate linked clauses."}]'::jsonb,
    '[{"id":"nw5","term":"repasar","pos":"verb","definition":"to review","example":"Voy a repasar estas palabras manana.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '7 days'
  ),
  (
    '20000000-0000-4000-8000-000000000006',
    '11111111-1111-4111-8111-111111111111',
    'French Conversation Club',
    'fr',
    'Hier soir jai participe a un club de conversation et jai parle pendant vingt minutes.',
    'Hier soir, jai participe a un club de conversation et jai parle pendant vingt minutes.',
    'Hier soir, jai participe a un club de conversation et jai reussi a parler pendant vingt minutes.',
    88,
    'Confident',
    'Yesterday evening I joined a conversation club and spoke for twenty minutes.',
    'Strong confidence. "reussi a" highlights achievement naturally.',
    '{"grammar":87,"vocabulary":88,"complexity":84}'::jsonb,
    '[{"id":"gs6","original":"Hier soir jai","corrected":"Hier soir, jai","note":"Comma after time phrase improves flow."}]'::jsonb,
    '[{"id":"nw6","term":"reussir","pos":"verb","definition":"to succeed","example":"Jai reussi a expliquer mon idee.","proficiency":"upper-intermediate"}]'::jsonb,
    'fr',
    'en',
    'en,fr',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '5 days'
  ),
  (
    '20000000-0000-4000-8000-000000000007',
    '11111111-1111-4111-8111-111111111111',
    'Morning Routine',
    'es',
    'Me desperte temprano, hice ejercicio y despues escribi dos parrafos en espanol.',
    'Me desperte temprano, hice ejercicio y despues escribi dos parrafos en espanol.',
    'Me desperte temprano, hice ejercicio y luego escribi dos parrafos en espanol.',
    87,
    'Determined',
    'I woke up early, exercised, and then wrote two paragraphs in Spanish.',
    'Natural sequence markers. Great consistency with daily writing habit.',
    '{"grammar":86,"vocabulary":88,"complexity":82}'::jsonb,
    '[{"id":"gs7","original":"despues","corrected":"luego","note":"Both are correct; vary connectors for style."}]'::jsonb,
    '[{"id":"nw7","term":"parrafo","pos":"noun","definition":"paragraph","example":"Escribi un parrafo sobre mi dia.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '3 days'
  ),
  (
    '20000000-0000-4000-8000-000000000008',
    '11111111-1111-4111-8111-111111111111',
    'Reading in French',
    'fr',
    'Je lis un roman court avant de dormir pour ameliorer mon vocabulaire.',
    'Je lis un roman court avant de dormir pour ameliorer mon vocabulaire.',
    'Je lis un petit roman avant de dormir afin dameliorer mon vocabulaire.',
    85,
    'Reflective',
    'I read a short novel before sleeping to improve my vocabulary.',
    'Very clear sentence. "afin de" adds a slightly more formal register.',
    '{"grammar":85,"vocabulary":86,"complexity":81}'::jsonb,
    '[{"id":"gs8","original":"pour ameliorer","corrected":"afin dameliorer","note":"Optional style upgrade for formal writing."}]'::jsonb,
    '[{"id":"nw8","term":"roman","pos":"noun","definition":"novel","example":"Ce roman est facile a suivre.","proficiency":"intermediate"}]'::jsonb,
    'fr',
    'en',
    'en,fr',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '2 days'
  ),
  (
    '20000000-0000-4000-8000-000000000009',
    '11111111-1111-4111-8111-111111111111',
    'Family Dinner',
    'es',
    'Anoche cenamos juntos y hablamos sobre nuestros planes para las vacaciones.',
    'Anoche cenamos juntos y hablamos sobre nuestros planes para las vacaciones.',
    'Anoche cenamos en familia y conversamos sobre nuestros planes para las vacaciones.',
    89,
    'Happy',
    'Last night we had dinner together and talked about our vacation plans.',
    'Great narrative sentence with good tense control.',
    '{"grammar":89,"vocabulary":90,"complexity":85}'::jsonb,
    '[{"id":"gs9","original":"hablamos","corrected":"conversamos","note":"Alternative verb for variety."}]'::jsonb,
    '[{"id":"nw9","term":"vacaciones","pos":"noun","definition":"vacation or holidays","example":"Las vacaciones empiezan en julio.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now() - interval '1 days'
  ),
  (
    '20000000-0000-4000-8000-000000000010',
    '11111111-1111-4111-8111-111111111111',
    'Tonight Check-in',
    'es',
    'Hoy practique treinta minutos y aprendi dos palabras nuevas que quiero usar manana.',
    'Hoy practique treinta minutos y aprendi dos palabras nuevas que quiero usar manana.',
    'Hoy practique durante treinta minutos y aprendi dos palabras nuevas que quiero usar manana.',
    90,
    'Confident',
    'Today I practiced for thirty minutes and learned two new words that I want to use tomorrow.',
    'Excellent self-reflection and clear plan for tomorrow.',
    '{"grammar":90,"vocabulary":89,"complexity":86}'::jsonb,
    '[{"id":"gs10","original":"practique treinta minutos","corrected":"practique durante treinta minutos","note":"Add preposition for a natural duration phrase."}]'::jsonb,
    '[{"id":"nw10","term":"manana","pos":"adverb","definition":"tomorrow","example":"Manana escribire otra entrada.","proficiency":"intermediate"}]'::jsonb,
    'es',
    'en',
    'en,es',
    'on_demand',
    'intermediate',
    'mock',
    'seed',
    now()
  );

insert into public.user_vocabulary (
  id,
  user_id,
  entry_id,
  term,
  language,
  part_of_speech,
  definition,
  reading,
  example_sentence,
  status,
  ai_example_sentences,
  ai_definitions,
  ai_synonyms,
  ai_antonyms,
  ai_related_phrases,
  ai_cultural_note,
  ai_pronunciation_guide,
  emotion_tone,
  mnemonic,
  emoji,
  source_model,
  created_at
)
values
  (
    '30000000-0000-4000-8000-000000000001',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000001',
    'meta',
    'es',
    'noun',
    'goal or target',
    null,
    'Mi meta es escribir todos los dias.',
    'learning',
    '["Mi meta de esta semana es escribir cinco entradas.","Una meta pequena cada dia produce progreso grande."]'::jsonb,
    '[{"part_of_speech":"noun","definition":"objetivo que quieres lograr"}]'::jsonb,
    '["objetivo","proposito"]'::jsonb,
    '["improvisacion"]'::jsonb,
    '["cumplir una meta","marcar una meta"]'::jsonb,
    'In Spanish learning contexts, meta is common in study plans and productivity conversations.',
    'MEH-tah',
    'motivational',
    'Think of a finish line you move toward each day.',
    '🎯',
    'seed',
    now() - interval '11 days'
  ),
  (
    '30000000-0000-4000-8000-000000000002',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000002',
    'verduras',
    'es',
    'noun',
    'vegetables',
    null,
    'Compre verduras para preparar sopa.',
    'saved',
    '["Las verduras frescas mejoran el sabor de la sopa."]'::jsonb,
    '[{"part_of_speech":"noun","definition":"vegetales comestibles"}]'::jsonb,
    '["vegetales","hortalizas"]'::jsonb,
    '["carne"]'::jsonb,
    '["verduras de hoja","verduras de temporada"]'::jsonb,
    'In many countries, "verduras" often refers to cooked vegetables in home meals.',
    'behr-DOO-rahs',
    'neutral',
    'Picture a green market stand full of colors.',
    '🥦',
    'seed',
    now() - interval '10 days'
  ),
  (
    '30000000-0000-4000-8000-000000000003',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000003',
    'medianoche',
    'es',
    'noun',
    'midnight',
    null,
    'Volvimos a casa despues de la medianoche.',
    'learning',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '9 days'
  ),
  (
    '30000000-0000-4000-8000-000000000004',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000004',
    'expression',
    'fr',
    'noun',
    'expression or phrase',
    null,
    'Cette expression est facile a memoriser.',
    'saved',
    '["Cette expression revient souvent dans les articles.","Jai utilise cette expression au club de conversation."]'::jsonb,
    '[{"part_of_speech":"noun","definition":"maniere de formuler une idee"}]'::jsonb,
    '["formule","locution"]'::jsonb,
    '["silence"]'::jsonb,
    '["expression idiomatique","expression courante"]'::jsonb,
    'French learners often collect useful expressions instead of isolated words.',
    'eks-pre-syon',
    'curious',
    'An expression is a ready-made language tool.',
    '💬',
    'seed',
    now() - interval '8 days'
  ),
  (
    '30000000-0000-4000-8000-000000000005',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000005',
    'repasar',
    'es',
    'verb',
    'to review or revise',
    null,
    'Voy a repasar mis notas esta noche.',
    'mastered',
    '["Antes del examen, siempre repaso el vocabulario.","Repasar en voz alta ayuda a recordar mejor."]'::jsonb,
    '[{"part_of_speech":"verb","definition":"volver a estudiar algo"}]'::jsonb,
    '["revisar","practicar"]'::jsonb,
    '["olvidar"]'::jsonb,
    '["repasar apuntes","repasar para un examen"]'::jsonb,
    'Repasar is commonly used by students preparing for tests in Spanish-speaking schools.',
    'reh-pah-SAHR',
    'focused',
    'Re-pass = go over the material one more pass.',
    '📚',
    'seed',
    now() - interval '7 days'
  ),
  (
    '30000000-0000-4000-8000-000000000006',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000006',
    'reussir',
    'fr',
    'verb',
    'to succeed',
    null,
    'Jai reussi a parler sans traduire.',
    'learning',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '5 days'
  ),
  (
    '30000000-0000-4000-8000-000000000007',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000007',
    'parrafo',
    'es',
    'noun',
    'paragraph',
    null,
    'Escribi un parrafo sobre mi rutina.',
    'saved',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '3 days'
  ),
  (
    '30000000-0000-4000-8000-000000000008',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000008',
    'roman',
    'fr',
    'noun',
    'novel',
    null,
    'Je lis un roman avant de dormir.',
    'saved',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '2 days'
  ),
  (
    '30000000-0000-4000-8000-000000000009',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000009',
    'vacaciones',
    'es',
    'noun',
    'vacations or holidays',
    null,
    'Estamos planeando vacaciones en la costa.',
    'saved',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now() - interval '1 day'
  ),
  (
    '30000000-0000-4000-8000-000000000010',
    '11111111-1111-4111-8111-111111111111',
    '20000000-0000-4000-8000-000000000010',
    'manana',
    'es',
    'adverb',
    'tomorrow',
    null,
    'Manana voy a escribir otra entrada.',
    'learning',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    now()
  );
