version: '3'

services:
  api:
    build:
      context: ./backend
      args:
        - PASSED_HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - PYTHONUNBUFFERED=1
      - USE_MISTRAL=${USE_MISTRAL}
      - USE_TRANSFORMERS_ONLY=false
      - MISTRAL_MODEL_PATH=/app/mistral_models
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - mistral_models:/app/mistral_models
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mistral_models:
    driver: local 