"""
Pydantic schemas for Gemini structured-output feedback.

These models define the JSON contract for the journal feedback call.
They intentionally omit the translation field (translation is handled by Lara
in a later PR) and keep the same field names the frontend already consumes.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class Rubric(BaseModel):
    """Detailed scoring rubric for grammar, vocabulary, and complexity."""
    grammar: int = Field(..., ge=0, le=100, description="Grammar score (0-100)")
    vocabulary: int = Field(..., ge=0, le=100, description="Vocabulary score (0-100)")
    complexity: int = Field(..., ge=0, le=100, description="Complexity score (0-100)")


class GrammarSuggestion(BaseModel):
    """A single grammar or style suggestion."""
    original: str = Field(..., description="The original problematic text snippet")
    corrected: str = Field(..., description="The suggested correction")
    note: str = Field(..., description="Explanation of the correction")


class NewWord(BaseModel):
    """A new or notable vocabulary word identified in the entry."""
    term: str = Field(..., description="The word or phrase")
    reading: Optional[str] = Field(None, description="Pronunciation or reading aid")
    pos: str = Field(..., description="Part of speech (e.g., noun, verb, adjective)")
    definition: str = Field(..., description="Definition in the appropriate language")
    example: str = Field(..., description="Example sentence using the word")
    proficiency: str = Field(..., description="Estimated proficiency level")


class GeminiJournalFeedback(BaseModel):
    """Response schema sent to Gemini; provenance flags are set by the server, never the model."""
    corrected: str = Field(..., description="Grammar-corrected version of the entry")
    rewrite: str = Field(..., description="Native-like rewrite")
    score: int = Field(..., ge=0, le=100, description="Overall fluency score (0-100)")
    tone: str = Field(..., description="Detected emotional tone or style")
    explanation: str = Field(..., description="Explanation of corrections and learning points")
    rubric: Rubric = Field(..., description="Detailed scoring breakdown")
    grammar_suggestions: List[GrammarSuggestion] = Field(default_factory=list)
    new_words: List[NewWord] = Field(default_factory=list)


class JournalFeedback(GeminiJournalFeedback):
    """Journal feedback plus server-assigned provenance."""
    is_mock: bool = Field(default=False, description="True when this feedback was generated by the mock provider")
