name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:   # lightweight placeholder for Supabase
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports: [5432:5432]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run Pytest
        run: |
          cd backend
          pytest -q
      - name: Install & type‑check frontend
        run: |
          cd frontend
          npm ci
          npm run type-check 